#
###################################
# Site wide configuration
####################################
#
title: I'm just sayin!
email: john.griffith8@gmail.com
description: Random, sometimes shallow thoughts about stuff.
url: https://j-griffith.github.io/archive


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Denver
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: John Griffith
  avatar: avatar.jpg
  bio: "Sofware Developer, Horseman, Sailor and Fly Fisherman."
  disqus-shortname: jgriffith
  twitter: jdg_8
  google:
    plus: JohnGriffith8
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: j-griffith
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: john-griffith-06080713
