# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Griffs github blog
tagline:             Random babbling
url:                 http://j-griffith.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Griffith
  url:               https://twitter.com/jdg_8
  email:             john.griffith8@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/j-griffith/j-griffith.github.io
